export var trials = {
    "events": [
        // scenario 1
        "你发现一个平常你当做朋友的人却在背后说你坏话",
        "同事请你出去喝杯咖啡",
        "你给朋友发消息寻求帮助，但 ta 没有回复",
        "你从超市购物回来，却发现自己忘买了一件必需品",
        " 你让同事给你写推荐信，但他们拒绝了",
        "You'd like to be more engaged in your local community",
        " 你给朋友发了一条欠缺思考的消息，ta 却马上回复了",
        "你为某项活动提出的建议获得的票数最少",
        "你收到同事对你工作表现的匿名反馈，内容是对你的赞扬",
        " 你尝试了一道复杂的新食谱，结果味道很棒",
        " 和你一起上学的人主动过来询问你过得怎么样",
        "你参加了工作中的小测验，答对了很多问题，最终你的团队获胜",
        " You start to fill out some paperwork for your bank but don't finish",
        "一个你认为关系很好的朋友生日聚会时却没有邀请你",
        " 你整理了一大篮子需要洗的衣服",
        "你发现你的上级领导想要提拔你",
        " 一位同事要求除你之外的所有工作人员帮助他们审查求职申请表",
        "你对着马路对面的熟人微笑，但 ta 没有回应你",
        "你没有完成你需要完成的工作量",
        " 你在商店里寻求帮助，并设法马上找到你需要的东西",
        " 你告诉你亲近的朋友你很崇拜他们，但ta却没有回复你同样的话",
        "你邻居家的小孩向你请教一道数学题，你很轻松地帮 ta 解决了问题",
        "你路过一家离公司很近的餐馆，发现你的同事一起吃饭却没有叫你",
        " 你和你的朋友们做一个普通知识测试，你的得分最低",
        "一个朋友告诉你，你总是能让 ta 笑",
        "你刚要准备洗碗，却打碎了一个盘子",
        " 你非常在乎的人突然打电话跟你聊天",
        " You have to fill in some long and boring paperwork, but manage to get it all done",
        "你在小组会议中发言并得到了大家的掌声",
        "一个同事告诉你 ta 喜欢你在身边",
        " 你没能在重要的截止日期前完成你需要做的一切工作",
        "你身边的人告诉你，他们很崇拜你",
        // scenario 2
        "一位朋友告诉你，和你交谈的时候让他们感觉很愉快",
        " Someone you met at an evening class suggests getting together for coffee",
        " 你在街上看到一个朋友，但他们似乎不理你",
        "你很轻松地完成了一个拼图游戏",
        " 你无意中听到一个朋友告诉别人你不可信任",
        "当你预定一项工作活动时，你很难计算出每个人需要付多少钱",
        " 你被要求为当地社区组织一次社交活动", 
        "你发现自己被推荐担任工作中的领导职位",
        " 一位同事请求你帮忙写求职申请，因为你写得很好",
        "你提交了一份加入当地社区活动团体的申请，但没有收到任何回复",
        " 你把一整个水槽都洗干净了",
        "你的朋友给你寄了一张卡片，感谢你在困难时期陪伴在他们身边",
        "你发现你没有被邀请参加下班后同事间的娱乐活动",
        "你在课堂上展示自己的作品，但是没有得到多少积极的反馈",
        " 你向杂志社提交了一篇文章，但是被退稿了",
        "你身边的人告诉你，你一点也不幽默",
        " 你买了一些做晚饭需要的食材",
        " 你想报名参加兴趣班，但意识到你已经错过了最后期限",
        " 你发现你忘记晾昨天洗的衣服了",
        " 朋友送你花，没什么特别的原因",
        " 你试着走一条新的捷径回家，结果却迷路了",
        "你的同事告诉你，ta 相信你的判断",
        "你发现有人联系了你的上司，为了称赞你为他们所做的工作",
        "你非常亲近的人把你私下告诉他们的事情告诉了别人",
        "你身边的人告诉你，ta 认为你是一个榜样",
        " 一个你不太熟悉的同事选择和你一起吃午饭",
        " You feel like you don't know your neighbours as well as you'd like to",
        "你无意中听到同事在背后议论你",
        " Everyone at work is asked to do a lateral thinking test and you score poorly",
        "你在工作会议中做报告，但似乎没人认真听",
        "你成功地掌握了一门新语言中的一些短语",
        " 你在没有任何帮助的情况下，尝试了一条新路线回家",
        // scenario 3
        " 一个朋友给你寄了一张明信片",
        " 你亲近的人送了你一份礼物，没什么特别的原因",
        " 你需要填写一些复杂的纳税申报表，但最终没有填完",
        "你在重要的事情上向朋友寻求帮助，但他们说他们太忙了",
        "你亲近的人告诉你他们信任你",
        " 你注意到，你上学那一年的人在网上进行着活跃的对话，而你却没有参与其中",
        " You fold and put away a load of laundry",
        " You attempt a sudoko puzzle but can't finish it",
        "你正在会议上发言，但是感觉人们对你要说的话不感兴趣",
        "你从老板那里得到了出色的绩效评价",
        "你把不同颜色的衣服都扔进洗衣机里了，结果衣服串色了",
        "A friend tells you that you are being difficult",
        "你发现有个同事在业绩评估中给你的分数很低",
        "你发现自己通过了一项非常困难的职业资格考试",
        "朋友告诉你，你是他们的好朋友",
        "你看到一个非常亲密的朋友并向他们挥手，但是他们没有回应",
        " 你发现有人向你的领导抱怨你的工作质量差",
        " 一个同事特别想让你加入他们的团队参加一项活动",
        " You feel like you'd like to have more hobbies",
        "你没有获得对职场文化贡献的奖项",
        "你的同事告诉你，他们认为你值得信赖",
        " 你每周进行一次大型购物，并且没有遗漏任何要买的东西",
        " You fix something around the house that you have been meaning to get done for a while",
        " Someone you are very close to doesn't ask you to speak at their wedding",
        " 工作日吃午饭时，没有同事和你坐一起",
        " 你正在努力学习一门新的语言，但是今天似乎想不起任何短语",
        " 你被推选出来成为当地社区的代表",
        " 你向一个陌生人问路，并成功地照着做了",
        " 你在商店里寻求帮助，但觉得店员无视你",
        "一位同事评价你最近的工作质量很高",
        " Someone you met in an art class messages you to ask how you are",
        " You manage to solve a difficult puzzle in the weekend paper",
        // scenario 4
        " 你自愿加入当地社区组织",
        "你发现自己在工作中很难达到目标",
        " 你曾希望在工作中获得奖项提名，但没有人推荐你",
        "你想在当地社区小组中担任一项职务，但是没有人推荐你",
        "你非常在意的人没有回复你的电话和短信",
        "同事告诉你，他们想邀请你一块参加一场工作聚会",
        "你给报社写的一篇稿件被选中发表",
        " 你告诉你亲近的人你崇拜他们，但他们没有回应你相同的话",
        "你关心的人会在忙碌的一天中抽出时间来看望你",
        "你忘记自己把食物放在烤箱里，结果它烤焦了",
        "你试图在商店里找东西，但是没有引起任何人的注意",
        " You put together a simple dinner you have cooked several times before",
        "你发现一个朋友正在举行聚会，但没有邀请你",
        " 你在工作中一直在做一个困难的项目，但设法完成了你需要做的一切",
        "你身边的人告诉你，ta 真希望自己像你一样",
        "你希望有时间学习一门新的语言或技能",
        "你无意中听到一位同事告诉别人 ta 不太喜欢你",
        "一位同事告诉你，他们特别感谢你对他们工作的反馈意见，因为这很有帮助",
        " 你参加了一个兴趣班的试听课",
        "一个朋友告诉你，你是个很好的人",
        "你发现一个同事推荐你获得工作表现优秀奖",
        " 邻居邀请你到他们家聊天",
        " 你试着在脑子里计算出每个人需要为晚餐付多少钱，但是发现有点困难",
        " 一个朋友告诉你，ta 认为你不诚实",
        "一个朋友突然打电话给你，想知道你最近过得怎么样",
        " At a work-related social event, people are slow to volunteer to be on your team",
        "你在赴约的路上搭错了交通工具，所以迟到了",
        "你需要分摊午餐的账单，并在脑子里准确地计算出了每个人应付的费用",
        "你成功地记住了以前只去过一次的地方的路线",
        "你发现你没有通过你参加的专业考试",
        "你的同学没有回复你发的消息",
        "你在课堂上展示了自己的作品，得到了同学们的高度赞扬"
    ],

    "int_glob": [
        // scenario 1
        "我的朋友并不是真的喜欢我",
        "人们去干一些事情的时候通常会把我包括在内",
        "我从来都不是我朋友的优先考虑对象",
        "我的记性不大好",
        " No one I work with respects me",
        "我和其他人相处不好",
        " My friends like me",
        "人们从不重视我的意见",
        "同事都很欣赏我",
        " I'm quick at picking up new things",
        " I'm the sort of person people like to keep in touch with",
        "我很聪明",
        " In general, I'm bad at seeing things through",
        "我感觉身边亲近的人其实并不喜欢我",
        " I'm good at getting things done",
        "我对自己的工作很在行",
        " People don't think I'm intelligent",
        "我遇到的人不喜欢我",
        "我做事情没有计划，效率低",
        " I usually don't find it hard to get people's attention",
        " People who know me well don't view me positively",
        "我很聪明",
        "人们通常不怎么喜欢我",
        " I'm not clever",
        "我很有幽默感",
        "我又笨又粗心",
        " People I'm close to generally miss me when I'm not around",
        " I'm good at seeing things through",
        "我很善于表达",
        "我是个有趣的人",
        " I always mess up important things",
        "我在乎的人都仰慕我",
        // scenario 2
        "我是人们看重的那种朋友",
        " I'm the kind of person people want to get to know",
        " I'm the kind of person people will avoid if they have a chance",
        "我很机智，反应迅速",
        " Fundamentally, I'm not a good person",
        "我很笨",
        " I'm the sort of person people like to involve in things",
        "我的同事都佩服我的工作能力",
        " I'm a good communicator",
        "我的某些地方让别人反感",
        " When I need to, I generally get things done",
        "I'm a good friend and people appreciate that",
        "别人不想与我相处",
        "我的作品很一般",
        " I am bad at communicating",
        "我确实不是一个有趣的人",
        " I'm organised",
        " I am disorganised",
        " I mess everything up, even basic tasks",
        " I'm the sort of person people think kindly of, even when absent",
        " I can't get anything right",
        "我的同事通常比较尊重我的判断",
        "我对自己的工作很在行",
        "在 ta 眼里，我没有重要到需要保守秘密的程度",
        "我是那种受人尊敬的人",
        " I'm the sort of person people like to be around",
        " I'm not interesting enough to get to know",
        "我不是那种受人尊敬的人",
        " I'm less intelligent than most people around me",
        "我不是那种人们会关注的人",
        "我很容易学会新东西",
        " I'm quick to pick things up",
        // scenario 3
        " I'm likeable",
        " People I'm close to care a lot about me",
        " I can't see anything through",
        "我不是我朋友优先考虑的对象",
        "我是一个值得信赖的人",
        " 我不是那种人们想与之保持联系的人",
        " I'm good at getting things done",
        " I'm stupid and lazy",
        "我不有趣",
        "我对自己的工作很擅长",
        "我把一切都搞砸了，即使是简单的事情",
        "我不是那种人们喜欢花时间和我在一起的人",
        "我工作能力比较差",
        "我很聪明，也很努力",
        "我确实是个不错的朋友",
        "我是那种人们会尽可能避开的人",
        " I'm bad at everything",
        " I'm the sort of person people like to be around",
        " I never put myself out there",
        "我不是那种与别人相处能够带来乐趣的人",
        "通常，即使是我不太熟悉的人也认为我不错",
        " I'm good at remembering things",
        " I'm the sort of person who gets things done",
        " People think I'm likely to embarass them",
        " I'm not fun or likeable",
        " I'm not smart",
        " I'm the kind of person people would like to have represent them",
        " I tend to pick things up quickly",
        " I'm not worth paying attention to",
        "我对自己的工作很擅长",
        " I'm the sort of person people often like straight away",
        " I'm intelligent",
        // scenario 4
        " I like to get involved in things",
        "我没有计划性，注意力不集中",
        " I'm not good at my job",
        "人们不想让我这样的人来代表他们",
        "我对我在乎的人来说并不重要",
        "我是那种人们会欢迎加入他们团队的人",
        "人们对我写的内容很感兴趣",
        " People I care about don't respect me",
        "我亲近的人有很多时间陪我",
        "我总是能把事情搞砸",
        "人们很容易忽视我",
        " I find it easy to get things done",
        "在内心深处，我当作朋友的人实际上并不喜欢我",
        " I'm a hard-worker who's good at seeing things through",
        "我身边的人对我的评价很好",
        " I'm not organised or motivated enough to learn something new",
        "人们往往不怎么喜欢我",
        "我是那种人们会重视我的意见的人",
        " I put myself out there",
        "我的朋友们对我评价很高",
        "我对自己的工作很擅长",
        " I'm the sort of person people who don't know me well feel comfortable with",
        " I'm not smart enough",
        " I'm basically not a good person",
        "我的朋友很关心我",
        " I'm not the sort of person people like to spend time with",
        "我什么都做不好",
        "我很聪明，头脑灵活",
        "我学得很快",
        "我很笨",
        "我不是那种别人会对我上心的人",
        "人们通常对我的作品很感兴趣"
    ],

    "int_spec": [
        // scenario 1
        "我最近可能做什么惹他们生气了",
        "我最近很努力地与 ta 交上了朋友",
        "我可能对他们最近的发的消息没有做出足够的回应",
        "我这次的计划可能不够周全",
        " This particular colleague doesn't seem to have a very high opinion of me",
        "最近，我没怎么和邻居打交道",
        " I've likely been messaging this person a lot recently",
        "可能我这次的建议不够好",
        "最近，我在某件工作上做得很好",
        " On this occasion, I managed to do everything right",
        " I probably used to get on well with this particular person",
        "这次测验的题目正好是我擅长的",
        " On this occasion, I let myself get distracted so didn't see it through",
        "我最近都没怎么联系过这个朋友",
        " I'm generally good at keeping things clean and tidy",
        "最近，我在工作中表现不错",
        " I probably haven't offered to help this person before",
        "我可能没有很热情地问候他们",
        "这周我可能把太多时间花在了不重要的事情上",
        " On this occasion, I happened to manage to get their attention",
        " I likely didn't communicate to them that I might like to hear the same said back to me",
        "我能够很轻松地解决这类简单的问题",
        "我最近没怎么和同事交谈",
        " I probably didn't try very hard this time",
        "我经常说一些话逗这个人笑",
        "当时，我可能没有足够专注于我正在做的事情",
        " This particular person has always seemed to care about me",
        " I can generally get my paperwork done on time",
        "在这次会议上，我确实提出了一些好的想法",
        "我似乎和这个人很合得来",
        " On this occasion, I was probably disorganised and didn't plan my time well",
        "可能我最近做了一件令我朋友印象深刻的事",
        // scenario 2
        "最近，我跟这个朋友交谈时很用心",
        " I probably made some kind of a connection with this particular person",
        " I probably haven't made much effort with this particular person recently",
        "这种游戏对于我来说并不困难",
        " I may have done something recently to annoy this person",
        "这次，我没有花心思去做这件事情",
        " I've put on some good events in the past",
        "最近，我在工作中表现不错",
        " I have helped people out with this kind of paperwork before",
        "我可能不小心把申请表交错了",
        " On this occasion, I decided to just get it out of the way",
        "最近，我确实花很多心思去陪伴这位朋友",
        "最近，我对这种活动没有表现出任何兴趣",
        "可能这次我没有很好地跟他们表达这幅画的意义",
        " I probably didn't spend enough time working this particular submission",
        "只是最近我在处理一些严肃对待的工作",
        " On this occasion, I remembered I needed to do something",
        "这次，我的计划不够周密，没有按时提交我的申请",
        " Yesterday, I was just too tired from everything else I had to do",
        " I probably did something for this particular friend recently",
        " This time, I didn't spend enough time working out the route",
        "最近，我帮助过这位朋友，给过ta一些建议",
        "这次工作我做的确实不错",
        "我最近可能做了什么冒犯这个人的事",
        "我最近一直在帮助这个人解决一些问题",
        " On this occasion, I probably appeared friendly",
        " I haven't had enough time recently to get involved in neighbourhood events",
        "我可能在某些方面对这个人不太友好",
        " For some reason I wasn't at my sharpest that day",
        "对于这次会议，我可能没有花足够的时间准备",
        "最近，我特别努力地下功夫学习这门语言",
        " On this occasion, I managed to work out where I needed to go",
        // scenario 3
        " Recently, I have been making an effort to talk with this particular friend",
        " I probably did something recently for this particular friend",
        " On this occasion, I didn't persevere enough",
        "我可能最近也没有给他们帮什么忙",
        "我最近一直在帮这个人处理一些私事",
        " I haven't made much effort to keep in touch with this particular group of people",
        " On this occasion, I just decided to get it out of the way",
        " On this occasion, I didn't try very hard",
        "对于这次会议，我没有很好地组织自己的发言",
        "最近，我在工作中的表现不错",
        "这次我可能有些心不在焉",
        "在我和这个人的最近一次谈话中，我可能给 ta 留下了冷漠的印象",
        "最近，我对于工作没有上心",
        "我为这次考试做了特别多的准备",
        "最近，我花了很多时间和这个人相处",
        "这次，我可能没有表现得很想与他们打招呼",
        " For this particular piece of work, I let my usual standards slip",
        " I'm quite good at this particular activity",
        " Recently, I haven't made enough effort to get involved in new things",
        "最近，我没怎么和同事们打交道",
        "最近，我帮助这个同事解决了一些私人问题",
        " This time, I made a particular effort to check everything I got off against my list",
        " On this occasion, I made a special effort to finally get it sorted",
        " I haven't invited this person to speak at any of my own special occasions",
        " I have probably done something to signal to my colleagues I prefer to be left alone",
        " Recently, I haven't spent enough time on this",
        " On this occasion, I made the effort to put myself forward",
        " On this occasion, I tried hard to memorise what they said",
        " I didn't try very hard to get the assistant's attention",
        "对于这次工作我非常用心",
        " On this occasion, I probably made a special effort to be friendly in class",
        " I'm generally good at this particular style of puzzle",
        // scenario 4
        " Recently, I have been pushing myself to try new things",
        "我最近没有很好地安排自己的时间",
        " I haven't told anyone else I was interested in being put forward",
        "最近，我很少参与社区活动",
        "可能我最近对 ta 的消息也不太上心",
        "最近，我对这位同事表现得十分友好",
        "这次我写的内容确实不错",
        " I probably didn't communicate to this person that it's important to me to be told this",
        "可能我最近也很关心这位朋友",
        "这次，我被一些不重要的事情分散了注意",
        "我可能没有做足够的事情来引起对方的注意",
        " I'm generally good at completing simple tasks",
        "可能最近我与 ta 相处不太融洽",
        " On this particular occasion, I made a plan and stuck to it",
        "最近，我非常用心地去帮助这个人",
        "最近，我没有足够的时间从事业余爱好或休闲活动",
        "我可能在某个时候对这位同事有点不太礼貌",
        "最近，我花时间帮助了这位同事的工作",
        " Recently, I have making a special effort to make time for hobbies",
        "最近，我努力花时间和这个人相处",
        "我最近在一项工作上很努力",
        " Recently, I have been making an effort to be pleasant to people in my local community",
        " On this occasion, I didn't feel like trying to work out a hard calculation in my head",
        " Recently, I have communicated badly with this friend about something",
        "我过去可能也为这位朋友做过同样的事",
        " On this occasion, I didn't show that I was keen to take part",
        "这次，我太马虎了，没有检查我的路线",
        "这次，我很努力地想把事情做好",
        "这次，我努力集中精力，成功回想起了这条路线",
        "我可能没有花足够的时间来准备这场考试",
        "我可能很久没联系过这个人了",
        "我为了这次演讲付出了很多努力，所以结果很好"
    ],

    "ext_glob": [
        // scenario 1
        "每个人或多或少都被人说过坏话",
        "同事们经常会时不时联络",
        "每个人都有忽略信息的时候",
        "通常，人们在做事的时候会忘记一些事情",
        " No one likes writing references",
        "There are always times when life gets in the way of things we'd like to prioritise",
        " People generally reply to messages from their friends quickly",
        "无论内容如何，人们通常都会选择票数多的建议",
        "人们对他人工作上的反馈通常是积极的",
        " People who can cook a bit can generally pick up new recipes easily",
        " People generally reach out to old classmates when they are feeling nostalgic",
        "工作中的小测验通常没那么难",
        " Boring tasks are always hard to complete",
        "有些场合你不能邀请别人",
        " Most people eventually manage to get their chores done",
        "团队中的每个人都可能在某个时候被提拔",
        " People often don't want to bother others with requests for help",
        "每个人有时都假装没看见他们认识的人",
        "有时候生活琐事会妨碍工作",
        " In general, retail workers look out for potential customers",
        " Everyone misreads social cues sometimes",
        "大多数和我同龄的人应该都能解决这些问题",
        "人们并不总是记得邀请所有他们想邀请的人",
        " Quizzes often aren't matched well to different people's general knowledge",
        "人们通常会时不时地称赞他们的朋友",
        "家务活通常很无聊，所以很容易分心",
        " People generally feel the need to keep up with people they are close to",
        " Everyone eventually gets through their paperwork",
        "在这种情况下，人们往往会表现得很有礼貌",
        "同事往往会对与他们共事的人很有礼貌",
        " There are always going to be weeks when you try to do too much",
        "人们对亲近的人说好话并不少见",
        // scenario 2
        "人们经常对亲近的人说好话",
        " Most people at evening classes are probably looking to meet people",
        " Often, people aren't sure if they've seen someone they know or not",
        "拼图游戏本来就是为大多数人设计的",
        " Everyone says thoughtless things about others sometimes",
        "有些问题通常不值得费心去解决",
        " Everyone is probably asked to organise these at some point",
        "工作中，大多数人都有可能在某个时候被提拔",
        " Everyone probably got asked for their input",
        "提交申请的应用程序系统通常比较复杂，有些信息可能会丢失",
        " Most people eventually get round to doing their housework",
        "人们为自己朋友做好事很常见",
        "每个人有时都会忘记把某人包括在内",
        "对于不怎么熟悉的人的作品，人们往往不太感兴趣",
        " Often there are many entries to competitions, and the choice of winner is somewhat random",
        "每个人都有不同的幽默感",
        " People generally remember that they need to eat",
        " Everyone misses deadlines sometimes",
        " Often, there are more important things to think about than household chores",
        " It's not uncommon for people to do nice things for their friends",
        " Everyone gets lost sometimes",
        "人们往往对同事有礼貌",
        "有些人很友善，喜欢给予别人积极的反馈",
        "人们经常不小心泄露别人的秘密",
        "人们经常对亲近的人说好话",
        " Some colleagues try and be friendly with everyone",
        " People often feel like they don't want to interefere in others' lives",
        "人们通过谈论同事来发泄情绪并不少见",
        " Tests are often harder than people think",
        "人们在听工作报告时经常感到无聊",
        "任何人都能记住几个基本短语",
        " People can generally navigate different ways through places they know well",
        // scenario 3
        " In general, people do nice things for their friends",
        " People often do nice things for their friends",
        " Paperwork is often hard and off-putting",
        "有时人们太忙或有自己的心事，无法成为他们想成为的好朋友",
        "人们经常对亲近的人说好话",
        " People often lose touch with their contemporaries over time",
        " People generally get their housework done eventually",
        " Puzzles can often be tedious and not fun",
        "人们通常对其他人在会议上的发言不感兴趣",
        "人们通常喜欢给予积极的评价",
        "人们通常有比家务更重要的事情要考虑",
        "人们对朋友无意中说一些伤人的话是很常见的",
        "大家可能得分都很低",
        "一般来说，举办考试的官方人员希望考生通过这些测试",
        "人们总是不时地对他们的朋友说些好话",
        "人们常常注意不到在大街上向他们招手的人",
        " There will always be days when you don't feel you were able to do your best",
        " Colleagues generally try and include everyone in team events",
        " Everyone lets life get in the way of things we value sometimes",
        "人们并不总是认可别人的贡献",
        "同事往往对与他们共事的人很礼貌",
        " Generally, people are able to remember when they have a list in front of them",
        " Everyone generally can get their household jobs done",
        " It's common to not be able to include everyone you want in special occasions",
        " People are often wary of approaching people they don't know",
        " Learning new things is generally hard",
        " Most people probably get asked at some point",
        " Most people are able to follow simple directions",
        " Working in shops is a busy job and everyone gets ignored sometimes",
        "同事往往对与他们共事的人说话很友好",
        " Most people at evening classes are probably looking to make friends",
        " These puzzles are probably designed to be solveable by most people",
        // scenario 4
        " Everyone in my area was probably automatically invited to join",
        "每个人都会有生活琐事妨碍工作的时候",
        " People are generally not good at recognising others' achievements",
        "人们一般不会去问谁愿意被推选出来做事情",
        "人们往往过于专注于自己的问题，以至于连一些的消息都顾不上回复",
        "同事们通常会尽可能让每个人都参加团队活动",
        "通常，出版物会尽可能多地发表稿件",
        " People are often too wrapped up in their own concerns to realise they have neglected others' feelings",
        "人们为朋友做些好事并不少见",
        "每个人都有比做饭更重要的事情需要考虑",
        "在商店工作的人们经常有很多事情要做，很难引起他们的注意",
        " Almost everyone can get simple things done when they have to",
        "人们经常不小心漏掉一些想要邀请的人",
        " People can generally get things done when they have to",
        "大多数人都会时不时地对他们的朋友说些好话",
        " People often find it hard to find time for hobbies or leisure activities",
        "当人们认为别人听不见的时候，他们经常漫不经心地谈论他人",
        "人们通常喜欢得到很多反馈",
        " Everyone was probably asked to sign up",
        "人们通常会时不时地称赞他们的朋友",
        "大多数人都可能在某个时候获得这些奖项的提名",
        " In general people are polite to their neighbours",
        " People often fail when they try and calculate things by themselves",
        " It's not uncommon for people to say unintentionally hurtful things",
        "人们通常会时不时地联系他们的朋友",
        " People often don't like to volunteer during work events",
        "每个人都会有时搞错路线",
        "通常，人们都可以做到这种简单的事情",
        "人们通常能记住一次简单的行程",
        "通常，专业考试都会设置得比较难",
        " Lots of people don't use particular social media very often",
        "一般来说，人们对别人的作品往往很有礼貌"
    ],

    "ext_spec": [
        // scenario 1
        "我的朋友可能只是心情不好，在发泄怨气",
        "这位同事可能出于某种原因想给人留下好印象",
        "我的朋友可能太忙了，现在没时间回复",
        "这次可能是某人或某事分散了我的注意力",
        " 这个人现在可能还有很多其他事情要做",
        "最近发生了很多其他事情",
        " 我的朋友可能刚好在看手机",
        "那天可能碰巧别人提出了一个更好的建议",
        "这位同事可能对每个人都很好",
        " This particular recipe was actually not that hard",
        " This person is probably trying to organise something specific, like a class reunion",
        "这个小测验可能很简单",
        " In this case, the paperwork was more complicated than it needed to be",
        "在这个特殊的场合，他们只能邀请一小部分人",
        " Someone proably reminded me to do this chore",
        "在这种情况下，他们可能只是不得不选择一个人",
        " They probably assumed I was too busy to help them right now",
        "他们可能心事重重，没看见我",
        "当时可能是有更重要的事情耽误了",
        " The assistant probably happened to be looking in my direction",
        " This particular friend probably assumed I already know they think well of me",
        "ta 问我的问题很简单",
        "我的同事可能在开会讨论某个我没有参与的工作项目",
        " This particular quiz didn't play to my strengths (e.g., was aimed at a different audience)",
        "这位朋友恰好和我有相似的幽默感",
        "可能当时是什么东西或者什么人吓到我了",
        " Someone probably reminded this person to get in touch with me",
        " I had probably recently been reminded to get it submitted",
        "这个小组的人都很友善，喜欢赞美别人",
        "这位同事可能想让我帮 ta 做点什么",
        " This particular week, things prevented me from functioning at my best",
        "这个人可能是想让我帮 ta 做点什么",
        // scenario 2
        "我的朋友可能是出于某种原因想鼓励我",
        " This person is probably new in town and looking for friends",
        " My friend was probably didn't see me",
        "这次的拼图可能比较简单",
        " My friend was just joking around during this conversation",
        "这次的活动内容很复杂，不把所有的项目都写出来是计算不出来的",
        " I've probably been asked to organise this specific event",
        "他们可能只是推荐了在这里待得最久的人",
        " This particular colleague needs a lot of help",
        "这一次，我的申请可能因为某些原因被耽误了",
        " It was probably my turn on the rota",
        "这次可能是别人建议他们这么做的",
        "我的同事可能认为我当时太忙了",
        "在这种情况下，人们可能会专注于其他事情（例如他们自己的演讲）",
        " In this case, something may have happened to my entry (e.g., it was delayed or mislaid)",
        "这个人可能没有与我相似的幽默感",
        " On this occasion, someone probably reminded me I needed to do this",
        " On this occasion, something else important probably got in the way of applying",
        " Something else was probably taking up my time just then",
        " Someone probably reminded this person they should get in touch with me",
        " There was probably something wrong with the directions I was given",
        "这个同事可能是想在之后请我帮个忙",
        "这个人可能出于某些原因才提出这样积极的反馈",
        "这个人可能不记得这件事是私下告诉他们的",
        "ta 可能认为我今天需要别人的鼓励",
        " This particular colleage is probably new and trying to make friends",
        " My current neighbours just prefer to keep themselves to themselves",
        "这个人可能今天过的比较糟，心情很差",
        " This particular test was probably overly harshly scored",
        "我的演讲可能比较靠后（例如，就在午饭前）",
        "这些短语都比较简单，很容易掌握",
        " On this occasion, I was probably not very far from home",
        // scenario 3
        " This particular person was probably sending out lots of cards on this day",
        " This particular person probably wants to ask for my help with something soon",
        " These particular forms were more probably more complicated than they needed to be",
        "这位朋友可能正在处理一些需要全神贯注的工作",
        "这位朋友可能正好想要倾诉一些事情",
        " These particular group of people were never part of my close circle",
        " Someone else probably asked me to do it this time",
        " This particular puzzle may have had a mistake in it",
        "这可能与演讲的时间有关（例如，演讲已接近尾声）",
        "我的老板可能希望我给他们一个好的评价",
        "可能在我洗衣服的时候出了些别的事打扰了我",
        "My friend is probably having a difficult time right now and is looking for more support from me",
        "这位同事那天可能搞错了（例如，把我误认为别人）",
        "这次的测验可能并不是多么困难",
        "这位朋友可能恰巧那天心情不错",
        "这位朋友那天可能在忙别的事",
        " On this particular day, something was probably distracting me from my work",
        " For this activity, they probably asked everyone present to take part",
        " Right now, I have too many other demands on my time from other people or tasks",
        "人们可能认为这个奖项不重要，所以没怎么去思考推选谁",
        "这位同事此刻可能想从我这里得到些什么",
        " Someone probably reminded me what I needed this time",
        " This was probably to avoid the prospect of doing a worse chore that day",
        " This person may have a large family so doesn't have space for everyone to speak at this event",
        " Someone may have mistakenly implied to these people that I prefer to eat alone",
        " Right now, I have a lot of other responsibilites that make it hard to commit time to learning",
        " This time, everyone else had probably already been asked",
        " This particular route was probably well sign-posted",
        " This particular assistant was probably in the middle of doing something else",
        "这位同事可能很快就会找我帮忙",
        " This particular person is probably new to the area and looking to make connections",
        " This puzzle was probably not actually that difficult",
        // scenario 4
        " A friend probably encouraged me to sign up",
        "这周碰巧发生了更重要的事情，所以耽误了工作",
        " People probably didn't realise I was eligible for this particular award",
        "这次竞争比较激烈，所以我没有被推选出来",
        "ta 现在可能暂时无法回复（例如，他们身体不适)",
        "这位同事可能是想讨好我",
        "可能我是唯一一个投稿这种文章类型的人",
        " Just then, they probably assumed I already thought they respected me",
        "可能是其他人建议这位朋友联系我的",
        "烤箱可能出了问题(例如，定时器没有响)",
        "那个助理可能正忙着处理别的事情",
        " This particular recipe was probably very straightforward",
        "我朋友以为我在这个日子没空",
        " On this occasion, I probably had help",
        "这次他们可能只是处于礼貌性的友好",
        "当前其他人或事占用了我太多的时间",
        "这个人似乎对每个人都很粗鲁",
        "这个人可能想让我帮他们做点什么",
        " I was probably prompted to go by someone else",
        "这个人可能需要我的帮助",
        "这位同事可能想要点回报",
        " This particular neighbour is probably lonely",
        " On this occasion, the problem was particularly hard",
        " This specific comment was probably the result of a misunderstanding",
        "可能是别人提醒 ta 联系我的",
        " No one wanted to take part in this particular social event",
        "这次可能出了些问题（例如，公共汽车前面牌子上的目的地是错的）",
        "这次因为有账单所以很容易计算",
        "这条路线上很可能有清晰的路标",
        "这个考试可能太难了",
        " This person probably doesn't use their account anymore",
        "这个班级的同学都很友好"
    ],

    "event_valence": [
        "negative",
        "positive",
        "negative",
        "negative",
        "negative",
        "negative",
        "positive",
        "negative",
        "positive",
        "positive",
        "positive",
        "positive",
        "negative",
        "negative",
        "positive",
        "positive",
        "negative",
        "negative",
        "negative",
        "positive",
        "negative",
        "positive",
        "negative",
        "negative",
        "positive",
        "negative",
        "positive",
        "positive",
        "positive",
        "positive",
        "negative",
        "positive",
        "positive",
        "positive",
        "negative",
        "positive",
        "negative",
        "negative",
        "positive",
        "positive",
        "positive",
        "negative",
        "positive",
        "positive",
        "negative",
        "negative",
        "negative",
        "negative",
        "positive",
        "negative",
        "negative",
        "positive",
        "negative",
        "positive",
        "positive",
        "negative",
        "positive",
        "positive",
        "negative",
        "negative",
        "negative",
        "negative",
        "positive",
        "positive",
        "positive",
        "positive",
        "negative",
        "negative",
        "positive",
        "negative",
        "positive",
        "negative",
        "negative",
        "positive",
        "negative",
        "negative",
        "negative",
        "positive",
        "positive",
        "negative",
        "negative",
        "positive",
        "negative",
        "negative",
        "positive",
        "positive",
        "positive",
        "negative",
        "negative",
        "negative",
        "positive",
        "positive",
        "negative",
        "positive",
        "positive",
        "positive",
        "positive",
        "negative",
        "negative",
        "negative",
        "negative",
        "positive",
        "positive",
        "negative",
        "positive",
        "negative",
        "negative",
        "positive",
        "negative",
        "positive",
        "positive",
        "negative",
        "negative",
        "positive",
        "positive",
        "positive",
        "positive",
        "positive",
        "negative",
        "negative",
        "positive",
        "negative",
        "negative",
        "positive",
        "positive",
        "negative",
        "negative",
        "positive"
    ]
};
